//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiHistory.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DataProductsEntities : DbContext
    {
        public DataProductsEntities()
            : base("name=DataProductsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HistorialT> HistorialT { get; set; }
    
        public virtual int ACOB_InsertHistory(string name, string id_video)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var id_videoParameter = id_video != null ?
                new ObjectParameter("id_video", id_video) :
                new ObjectParameter("id_video", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ACOB_InsertHistory", nameParameter, id_videoParameter);
        }
    
        public virtual ObjectResult<ACOB_SelectHistory_Result> ACOB_SelectHistory()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ACOB_SelectHistory_Result>("ACOB_SelectHistory");
        }
    }
}
